documentation:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - '*.md'
              - 'docs/**'

chore:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - '.github/**'
              - 'Makefile'
              - 'go.mod'
              - 'go.sum'
              - '*.yml'
              - '*.yaml'
