project_name: ci-result-to-slack
builds:
  - env: [CGO_ENABLED=0]
    main: ./cmd/ci-result-to-slack
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
  - image_templates: ["ghcr.io/salesforce/ci-result-to-slack:{{ .Version }}"]
    dockerfile: Dockerfile
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/salesforce/ci-result-to-slack
      - --label=org.opencontainers.image.source=https://github.com/salesforce/ci-result-to-slack
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=BSD-3-Clause
nfpms:
  - maintainer: Justin Harringa <jharringa@salesforce.com>
    description: Send your CI result to Slack upon pipeline completion
    homepage: https://github.com/salesforce/ci-result-to-slack
    license: BSD-3-Clause
    formats:
      - deb
      - rpm
      - apk