name: 'Build + Test'
on:
  push:
    paths-ignore:
      - 'CODE_OF_CONDUCT.md'
      - 'LICENSE.txt'
      - 'README.md'
      - 'SECURITY.md'
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.1
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: build and test binary
        run: make ci
      - name: GoReleaser Build
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --skip-publish --snapshot --rm-dist
