name: 'Build + Test'
on:
  push:
    paths-ignore:
      - 'CODE_OF_CONDUCT.md'
      - 'LICENSE.txt'
      - 'README.md'
      - 'SECURITY.md'
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.4.0
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: build and test binary
        run: make ci
      - name: GoReleaser Build
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --skip-publish --snapshot --rm-dist
