name: 'Build + Test'
on:
  push:
    paths-ignore:
      - 'CODE_OF_CONDUCT.md'
      - 'LICENSE.txt'
      - 'README.md'
      - 'SECURITY.md'
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: build and test binary
        run: make ci
      - name: docker build
        run: make local-docker-build
      - name: GoReleaser Build
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: build --rm-dist